### PR TITLE
car price prediction

### PR DESCRIPTION
**Pull request by samarth2727**
basic python ml project for beginners.

### CODE REVIEW

**Comment by samarth2727** [comment]
hi..! can you please check I have submitted car price prediction using python beginner level and a basic python number guessing game.

**Comment by aniketartani** [comment]
Ok i will

**Comment by aniketartani** [comment]
Please add these projects in the readme file too of this repository.

**Comment by samarth2727** [comment]
I am not able to edit your readme file

**Comment by aniketartani** [comment]
fork and make a Pull request.

**Comment by samarth2727** [comment]
Yes I did. May I ask you how did you add so many things in your profile
overview your profile really looks good.

**Comment by aniketartani** [comment]
using html :)

**Pull request merged**
